### ISSUE TITLE
feat: Nexus SDK documentation (MVP)

### ISSUE THREAD

**Issue by himanshugarg06** [bcnmy/documentation#32]
[Nexus documentation Table of contents
](https://www.notion.so/biconomy/Nexus-Documentation-TOC-2e472be76ca748a68485ee12721955e1)

[Preview](https://docs-devx.biconomy.io/nexus/overview)

Tutorial structure suggestion: https://github.com/wevm/viem/tree/main/examples

Relevant Slack thread: https://biconomyworkspace.slack.com/archives/CRZ4BSCUU/p1725270863169489

**Comment by Graeme-Code** [comment]
assumption that this is MVP docs. Please list whats in scope for MVP. Up to you if it should be tasks insdie of ticket or multiple issues. would prefer in multiple issues for sprint mgmt. @himanshugarg06 @joepegler
