### ISSUE TITLE
Add disconnect button and next tab in the privy demo

### ISSUE THREAD

**Issue by himanshugarg06** [bcnmy/documentation#36]
Currently users have to manually delete the application data in order to see the sign in flow. 

Also once user signs in, It shows the same sign in tab.

**Comment by TheDivic** [comment]
@himanshugarg06 what milestone could this be related to?

Take a look at other milestones on our project board for inspiration: https://github.com/orgs/bcnmy/projects/14/views/7

**Comment by himanshugarg06** [comment]
This is a fix required in one of our demos in docs. Have marked it Docs documentation.
